### PR TITLE
3 3.1.2 enter shipping information for buy

### PR DESCRIPTION
**Pull request by SeverinBuchser**
Created the shipping stage and everything with it. You can now define stages very easily. The stages have navigation and can emit data. The way the stage handles the data and navigates is up to the stage.

### Stagable
The `Stagable` is a directive. This directive can only be extended and not used. The first extension is the `BuyItemComponent`. This component defines two stages: `ShippingComponent` and `PaymentMethodComponent`. The `Stagable` directive now dynamically builds the components using a factory. The directive also assigns output emission and inputs to the stages.
### Stage
A stage extends the `StageNDEExtention` directive. These directives can also only be extended. The base class then provides all the different inputs and outputs which a stage needs to have. The stage then implements the `getData` method and can emit the data in one of its methods (there you can override the `nextStage` method to emit the data there). This is the only really important thing of the stages: Get data from the user. 
The stages have much more to them than the above.

### Map
The leaflet map is now implemented and uses the packages 'leaflet', 'esri-leaflet' and 'esri-leaflet-geocoder'. These are used to search for locations and also display the map much easier. There are a few classes which extend the base `Map` class. These allow for searching and displaying the locations you searched. The `MapComponent` then implements the extension with the most features. The `MapComponent` can display a default location by passing in a string. The `Location` class then searches for the location and displays the results on the map. You can also get search results form the map component. These results are emitted by the `searchResultsEmitter` `EventEmitter`

### CODE REVIEW

**Comment by medoparder** [comment]
Looks ok for me, code and also application. 
One thing: maybe we can add a button for cancel, if the user decides while the process to not buy the product?

**Comment by SeverinBuchser** [comment]
> One thing: maybe we can add a button for cancel, if the user decides while the process to not buy the product?
Will do

**Comment by medoparder** [comment]
The implementation from the last commit "Fix Map on product details and add map-search component" dont work. for example: when i have location "Bern" it shows in the product-details Singapore, when i change it to zürich the map changes but in a region in france

**Comment by medoparder** [comment]
The implementation from the last commit "Fix Map on product details and add map-search component" dont work properly. the problem is, that it finds more than one location with the name bern or zürich. (for expemple in singapore or portugal). so it takes these

**Pull request merged**
